### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by ClaudioRSGit** [henrique11varela/atec-t1-loja#1]
Hi Henrique, first of all congratulations for your first C++ project.
It's quite impressive how you got so far, but in my opinion the icing on the cake would be everything in English.
Keep up the great work.

**Comment by henrique11varela** [comment]
Will do!

**Comment by henrique11varela** [comment]
I think it's all done, so ill close the issue.
If you find anything wrong with it, or any suggestion please inform me!
